import { Users } from "lucide-react";

export type Presence = { scouted: string[]; generated: string[] };

const list = (names: string[]) =>
  names.length <= 2 ? names.join(" & ") : `${names.slice(0, 2).join(", ")} +${names.length - 2}`;

/** "Racheal scouted this · Also in HQ360 team's batches" — shown when other
 *  workspaces have the same author, so nobody chases a lead blind. */
export function PresenceNote({ presence }: { presence?: Presence | null | undefined }) {
  if (!presence || (!presence.scouted.length && !presence.generated.length)) return null;
  const parts = [
    presence.scouted.length ? `${list(presence.scouted)} scouted this` : "",
    presence.generated.length
      ? `${presence.scouted.length ? "also in" : "In"} ${list(presence.generated)}'s batches`
      : "",
  ].filter(Boolean);
  return (
    <span
      className="presence-note"
      title={[
        presence.scouted.length ? `Scouted by: ${presence.scouted.join(", ")}` : "",
        presence.generated.length ? `Generated by: ${presence.generated.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n")}
    >
      <Users size={12} aria-hidden="true" /> {parts.join(" · ")}
    </span>
  );
}
