// Regenerates src/data/industry-heads.ts from src/data/industries.ts.
// Run after editing industry SEO/FAQ copy: bun scripts/generate-industry-heads.ts
// (tests/industry-heads.test.ts fails if the two drift apart.)
import { writeFileSync } from "node:fs";
import { INDUSTRIES } from "../src/data/industries";

const heads = Object.fromEntries(
  INDUSTRIES.map((i) => [
    i.slug,
    { slug: i.slug, path: i.path, name: i.name, shortName: i.shortName, seo: i.seo, faqs: i.faqs },
  ]),
);
writeFileSync(
  "src/data/industry-heads.ts",
  `// GENERATED by scripts/generate-industry-heads.ts -- do not edit by hand.
// Just the fields industry route <head>s need, so route configs (which sit in
// the shared bundle every page loads) don't pull in all industry page copy.
import type { Industry } from "./industries";

export type IndustryHead = Pick<Industry, "slug" | "path" | "name" | "shortName" | "seo" | "faqs">;

export const INDUSTRY_HEADS: Record<string, IndustryHead> = ${JSON.stringify(heads, null, 2)};
`,
);
console.log(`Wrote ${INDUSTRIES.length} industry heads.`);
