/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as BookLaunchRouteImport } from './routes/book-launch'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GuaranteeRouteImport } from './routes/guarantee'
import { Route as HomeServicesRouteImport } from './routes/home-services'
import { Route as HvacRouteImport } from './routes/hvac'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LawFirmsRouteImport } from './routes/law-firms'
import { Route as LocalBusinessRouteImport } from './routes/local-business'
import { Route as MedSpasRouteImport } from './routes/med-spas'
import { Route as PlumbersRouteImport } from './routes/plumbers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RoofersRouteImport } from './routes/roofers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CapabilitiesIndexRouteImport } from './routes/capabilities.index'
import { Route as CapabilitiesSlugRouteImport } from './routes/capabilities.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as InsightsGlossaryRouteImport } from './routes/insights.glossary'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ApiAdminCaseStudiesRouteImport } from './routes/api/admin/case-studies'
import { Route as ApiAdminPortfolioRouteImport } from './routes/api/admin/portfolio'
import { Route as ApiAdminSessionRouteImport } from './routes/api/admin/session'
import { Route as ApiAdminTeamRouteImport } from './routes/api/admin/team'
import { Route as ApiAdminTestimonialsRouteImport } from './routes/api/admin/testimonials'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminUploadUrlRouteImport } from './routes/api/admin/upload-url'
import { Route as ApiPublicCaseStudiesRouteImport } from './routes/api/public/case-studies'
import { Route as ApiPublicGrowthAuditRouteImport } from './routes/api/public/growth-audit'
import { Route as ApiPublicInquiryRouteImport } from './routes/api/public/inquiry'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as ApiPublicPortfolioRouteImport } from './routes/api/public/portfolio'
import { Route as ApiPublicResourceRequestRouteImport } from './routes/api/public/resource-request'
import { Route as ApiPublicTeamRouteImport } from './routes/api/public/team'
import { Route as ApiPublicTestimonialsRouteImport } from './routes/api/public/testimonials'
import { Route as InsightsAnswersSlugRouteImport } from './routes/insights.answers.$slug'
import { Route as InsightsGuidesSlugRouteImport } from './routes/insights.guides.$slug'
import { Route as ApiAdminCaseStudiesIdRouteImport } from './routes/api/admin/case-studies.$id'
import { Route as ApiAdminCaseStudiesReorderRouteImport } from './routes/api/admin/case-studies.reorder'
import { Route as ApiAdminPortfolioIdRouteImport } from './routes/api/admin/portfolio.$id'
import { Route as ApiAdminPortfolioReorderRouteImport } from './routes/api/admin/portfolio.reorder'
import { Route as ApiAdminTeamIdRouteImport } from './routes/api/admin/team.$id'
import { Route as ApiAdminTeamReorderRouteImport } from './routes/api/admin/team.reorder'
import { Route as ApiAdminTestimonialsIdRouteImport } from './routes/api/admin/testimonials.$id'
import { Route as ApiAdminTestimonialsReorderRouteImport } from './routes/api/admin/testimonials.reorder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const BookLaunchRoute = BookLaunchRouteImport.update({
  id: '/book-launch',
  path: '/book-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteeRoute = GuaranteeRouteImport.update({
  id: '/guarantee',
  path: '/guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeServicesRoute = HomeServicesRouteImport.update({
  id: '/home-services',
  path: '/home-services',
  getParentRoute: () => rootRouteImport,
} as any)
const HvacRoute = HvacRouteImport.update({
  id: '/hvac',
  path: '/hvac',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LawFirmsRoute = LawFirmsRouteImport.update({
  id: '/law-firms',
  path: '/law-firms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalBusinessRoute = LocalBusinessRouteImport.update({
  id: '/local-business',
  path: '/local-business',
  getParentRoute: () => rootRouteImport,
} as any)
const MedSpasRoute = MedSpasRouteImport.update({
  id: '/med-spas',
  path: '/med-spas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlumbersRoute = PlumbersRouteImport.update({
  id: '/plumbers',
  path: '/plumbers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofersRoute = RoofersRouteImport.update({
  id: '/roofers',
  path: '/roofers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesIndexRoute = CapabilitiesIndexRouteImport.update({
  id: '/capabilities/',
  path: '/capabilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesSlugRoute = CapabilitiesSlugRouteImport.update({
  id: '/capabilities/$slug',
  path: '/capabilities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsGlossaryRoute = InsightsGlossaryRouteImport.update({
  id: '/insights/glossary',
  path: '/insights/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCaseStudiesRoute = ApiAdminCaseStudiesRouteImport.update({
  id: '/api/admin/case-studies',
  path: '/api/admin/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPortfolioRoute = ApiAdminPortfolioRouteImport.update({
  id: '/api/admin/portfolio',
  path: '/api/admin/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSessionRoute = ApiAdminSessionRouteImport.update({
  id: '/api/admin/session',
  path: '/api/admin/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTeamRoute = ApiAdminTeamRouteImport.update({
  id: '/api/admin/team',
  path: '/api/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestimonialsRoute = ApiAdminTestimonialsRouteImport.update({
  id: '/api/admin/testimonials',
  path: '/api/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadUrlRoute = ApiAdminUploadUrlRouteImport.update({
  id: '/api/admin/upload-url',
  path: '/api/admin/upload-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaseStudiesRoute = ApiPublicCaseStudiesRouteImport.update({
  id: '/api/public/case-studies',
  path: '/api/public/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGrowthAuditRoute = ApiPublicGrowthAuditRouteImport.update({
  id: '/api/public/growth-audit',
  path: '/api/public/growth-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInquiryRoute = ApiPublicInquiryRouteImport.update({
  id: '/api/public/inquiry',
  path: '/api/public/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortfolioRoute = ApiPublicPortfolioRouteImport.update({
  id: '/api/public/portfolio',
  path: '/api/public/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResourceRequestRoute =
  ApiPublicResourceRequestRouteImport.update({
    id: '/api/public/resource-request',
    path: '/api/public/resource-request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTeamRoute = ApiPublicTeamRouteImport.update({
  id: '/api/public/team',
  path: '/api/public/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestimonialsRoute = ApiPublicTestimonialsRouteImport.update({
  id: '/api/public/testimonials',
  path: '/api/public/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsAnswersSlugRoute = InsightsAnswersSlugRouteImport.update({
  id: '/insights/answers/$slug',
  path: '/insights/answers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsGuidesSlugRoute = InsightsGuidesSlugRouteImport.update({
  id: '/insights/guides/$slug',
  path: '/insights/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCaseStudiesIdRoute = ApiAdminCaseStudiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCaseStudiesRoute,
} as any)
const ApiAdminCaseStudiesReorderRoute =
  ApiAdminCaseStudiesReorderRouteImport.update({
    id: '/reorder',
    path: '/reorder',
    getParentRoute: () => ApiAdminCaseStudiesRoute,
  } as any)
const ApiAdminPortfolioIdRoute = ApiAdminPortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminPortfolioRoute,
} as any)
const ApiAdminPortfolioReorderRoute =
  ApiAdminPortfolioReorderRouteImport.update({
    id: '/reorder',
    path: '/reorder',
    getParentRoute: () => ApiAdminPortfolioRoute,
  } as any)
const ApiAdminTeamIdRoute = ApiAdminTeamIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminTeamRoute,
} as any)
const ApiAdminTeamReorderRoute = ApiAdminTeamReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ApiAdminTeamRoute,
} as any)
const ApiAdminTestimonialsIdRoute = ApiAdminTestimonialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminTestimonialsRoute,
} as any)
const ApiAdminTestimonialsReorderRoute =
  ApiAdminTestimonialsReorderRouteImport.update({
    id: '/reorder',
    path: '/reorder',
    getParentRoute: () => ApiAdminTestimonialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRoute
  '/authors': typeof AuthorsRoute
  '/book-launch': typeof BookLaunchRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/ecommerce': typeof EcommerceRoute
  '/faqs': typeof FaqsRoute
  '/guarantee': typeof GuaranteeRoute
  '/home-services': typeof HomeServicesRoute
  '/hvac': typeof HvacRoute
  '/industries': typeof IndustriesRoute
  '/law-firms': typeof LawFirmsRoute
  '/local-business': typeof LocalBusinessRoute
  '/med-spas': typeof MedSpasRoute
  '/plumbers': typeof PlumbersRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/reviews': typeof ReviewsRoute
  '/roofers': typeof RoofersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/glossary': typeof InsightsGlossaryRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/admin/case-studies': typeof ApiAdminCaseStudiesRouteWithChildren
  '/api/admin/portfolio': typeof ApiAdminPortfolioRouteWithChildren
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/team': typeof ApiAdminTeamRouteWithChildren
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/admin/upload-url': typeof ApiAdminUploadUrlRoute
  '/api/public/case-studies': typeof ApiPublicCaseStudiesRoute
  '/api/public/growth-audit': typeof ApiPublicGrowthAuditRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/portfolio': typeof ApiPublicPortfolioRoute
  '/api/public/resource-request': typeof ApiPublicResourceRequestRoute
  '/api/public/team': typeof ApiPublicTeamRoute
  '/api/public/testimonials': typeof ApiPublicTestimonialsRoute
  '/insights/answers/$slug': typeof InsightsAnswersSlugRoute
  '/insights/guides/$slug': typeof InsightsGuidesSlugRoute
  '/api/admin/case-studies/$id': typeof ApiAdminCaseStudiesIdRoute
  '/api/admin/case-studies/reorder': typeof ApiAdminCaseStudiesReorderRoute
  '/api/admin/portfolio/$id': typeof ApiAdminPortfolioIdRoute
  '/api/admin/portfolio/reorder': typeof ApiAdminPortfolioReorderRoute
  '/api/admin/team/$id': typeof ApiAdminTeamIdRoute
  '/api/admin/team/reorder': typeof ApiAdminTeamReorderRoute
  '/api/admin/testimonials/$id': typeof ApiAdminTestimonialsIdRoute
  '/api/admin/testimonials/reorder': typeof ApiAdminTestimonialsReorderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRoute
  '/authors': typeof AuthorsRoute
  '/book-launch': typeof BookLaunchRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/ecommerce': typeof EcommerceRoute
  '/faqs': typeof FaqsRoute
  '/guarantee': typeof GuaranteeRoute
  '/home-services': typeof HomeServicesRoute
  '/hvac': typeof HvacRoute
  '/industries': typeof IndustriesRoute
  '/law-firms': typeof LawFirmsRoute
  '/local-business': typeof LocalBusinessRoute
  '/med-spas': typeof MedSpasRoute
  '/plumbers': typeof PlumbersRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/reviews': typeof ReviewsRoute
  '/roofers': typeof RoofersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/glossary': typeof InsightsGlossaryRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog': typeof BlogIndexRoute
  '/capabilities': typeof CapabilitiesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/api/admin/case-studies': typeof ApiAdminCaseStudiesRouteWithChildren
  '/api/admin/portfolio': typeof ApiAdminPortfolioRouteWithChildren
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/team': typeof ApiAdminTeamRouteWithChildren
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/admin/upload-url': typeof ApiAdminUploadUrlRoute
  '/api/public/case-studies': typeof ApiPublicCaseStudiesRoute
  '/api/public/growth-audit': typeof ApiPublicGrowthAuditRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/portfolio': typeof ApiPublicPortfolioRoute
  '/api/public/resource-request': typeof ApiPublicResourceRequestRoute
  '/api/public/team': typeof ApiPublicTeamRoute
  '/api/public/testimonials': typeof ApiPublicTestimonialsRoute
  '/insights/answers/$slug': typeof InsightsAnswersSlugRoute
  '/insights/guides/$slug': typeof InsightsGuidesSlugRoute
  '/api/admin/case-studies/$id': typeof ApiAdminCaseStudiesIdRoute
  '/api/admin/case-studies/reorder': typeof ApiAdminCaseStudiesReorderRoute
  '/api/admin/portfolio/$id': typeof ApiAdminPortfolioIdRoute
  '/api/admin/portfolio/reorder': typeof ApiAdminPortfolioReorderRoute
  '/api/admin/team/$id': typeof ApiAdminTeamIdRoute
  '/api/admin/team/reorder': typeof ApiAdminTeamReorderRoute
  '/api/admin/testimonials/$id': typeof ApiAdminTestimonialsIdRoute
  '/api/admin/testimonials/reorder': typeof ApiAdminTestimonialsReorderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/agencies': typeof AgenciesRoute
  '/authors': typeof AuthorsRoute
  '/book-launch': typeof BookLaunchRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/ecommerce': typeof EcommerceRoute
  '/faqs': typeof FaqsRoute
  '/guarantee': typeof GuaranteeRoute
  '/home-services': typeof HomeServicesRoute
  '/hvac': typeof HvacRoute
  '/industries': typeof IndustriesRoute
  '/law-firms': typeof LawFirmsRoute
  '/local-business': typeof LocalBusinessRoute
  '/med-spas': typeof MedSpasRoute
  '/plumbers': typeof PlumbersRoute
  '/privacy': typeof PrivacyRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
  '/results': typeof ResultsRoute
  '/reviews': typeof ReviewsRoute
  '/roofers': typeof RoofersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capabilities/$slug': typeof CapabilitiesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/glossary': typeof InsightsGlossaryRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/capabilities/': typeof CapabilitiesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/api/admin/case-studies': typeof ApiAdminCaseStudiesRouteWithChildren
  '/api/admin/portfolio': typeof ApiAdminPortfolioRouteWithChildren
  '/api/admin/session': typeof ApiAdminSessionRoute
  '/api/admin/team': typeof ApiAdminTeamRouteWithChildren
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/admin/upload-url': typeof ApiAdminUploadUrlRoute
  '/api/public/case-studies': typeof ApiPublicCaseStudiesRoute
  '/api/public/growth-audit': typeof ApiPublicGrowthAuditRoute
  '/api/public/inquiry': typeof ApiPublicInquiryRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/api/public/portfolio': typeof ApiPublicPortfolioRoute
  '/api/public/resource-request': typeof ApiPublicResourceRequestRoute
  '/api/public/team': typeof ApiPublicTeamRoute
  '/api/public/testimonials': typeof ApiPublicTestimonialsRoute
  '/insights/answers/$slug': typeof InsightsAnswersSlugRoute
  '/insights/guides/$slug': typeof InsightsGuidesSlugRoute
  '/api/admin/case-studies/$id': typeof ApiAdminCaseStudiesIdRoute
  '/api/admin/case-studies/reorder': typeof ApiAdminCaseStudiesReorderRoute
  '/api/admin/portfolio/$id': typeof ApiAdminPortfolioIdRoute
  '/api/admin/portfolio/reorder': typeof ApiAdminPortfolioReorderRoute
  '/api/admin/team/$id': typeof ApiAdminTeamIdRoute
  '/api/admin/team/reorder': typeof ApiAdminTeamReorderRoute
  '/api/admin/testimonials/$id': typeof ApiAdminTestimonialsIdRoute
  '/api/admin/testimonials/reorder': typeof ApiAdminTestimonialsReorderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/authors'
    | '/book-launch'
    | '/coaches'
    | '/contact'
    | '/creators'
    | '/ecommerce'
    | '/faqs'
    | '/guarantee'
    | '/home-services'
    | '/hvac'
    | '/industries'
    | '/law-firms'
    | '/local-business'
    | '/med-spas'
    | '/plumbers'
    | '/privacy'
    | '/real-estate'
    | '/resources'
    | '/results'
    | '/reviews'
    | '/roofers'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/capabilities/$slug'
    | '/insights/$slug'
    | '/insights/glossary'
    | '/services/$slug'
    | '/work/$slug'
    | '/blog/'
    | '/capabilities/'
    | '/insights/'
    | '/services/'
    | '/work/'
    | '/api/admin/case-studies'
    | '/api/admin/portfolio'
    | '/api/admin/session'
    | '/api/admin/team'
    | '/api/admin/testimonials'
    | '/api/admin/upload'
    | '/api/admin/upload-url'
    | '/api/public/case-studies'
    | '/api/public/growth-audit'
    | '/api/public/inquiry'
    | '/api/public/newsletter'
    | '/api/public/portfolio'
    | '/api/public/resource-request'
    | '/api/public/team'
    | '/api/public/testimonials'
    | '/insights/answers/$slug'
    | '/insights/guides/$slug'
    | '/api/admin/case-studies/$id'
    | '/api/admin/case-studies/reorder'
    | '/api/admin/portfolio/$id'
    | '/api/admin/portfolio/reorder'
    | '/api/admin/team/$id'
    | '/api/admin/team/reorder'
    | '/api/admin/testimonials/$id'
    | '/api/admin/testimonials/reorder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/authors'
    | '/book-launch'
    | '/coaches'
    | '/contact'
    | '/creators'
    | '/ecommerce'
    | '/faqs'
    | '/guarantee'
    | '/home-services'
    | '/hvac'
    | '/industries'
    | '/law-firms'
    | '/local-business'
    | '/med-spas'
    | '/plumbers'
    | '/privacy'
    | '/real-estate'
    | '/resources'
    | '/results'
    | '/reviews'
    | '/roofers'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/capabilities/$slug'
    | '/insights/$slug'
    | '/insights/glossary'
    | '/services/$slug'
    | '/work/$slug'
    | '/blog'
    | '/capabilities'
    | '/insights'
    | '/services'
    | '/work'
    | '/api/admin/case-studies'
    | '/api/admin/portfolio'
    | '/api/admin/session'
    | '/api/admin/team'
    | '/api/admin/testimonials'
    | '/api/admin/upload'
    | '/api/admin/upload-url'
    | '/api/public/case-studies'
    | '/api/public/growth-audit'
    | '/api/public/inquiry'
    | '/api/public/newsletter'
    | '/api/public/portfolio'
    | '/api/public/resource-request'
    | '/api/public/team'
    | '/api/public/testimonials'
    | '/insights/answers/$slug'
    | '/insights/guides/$slug'
    | '/api/admin/case-studies/$id'
    | '/api/admin/case-studies/reorder'
    | '/api/admin/portfolio/$id'
    | '/api/admin/portfolio/reorder'
    | '/api/admin/team/$id'
    | '/api/admin/team/reorder'
    | '/api/admin/testimonials/$id'
    | '/api/admin/testimonials/reorder'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agencies'
    | '/authors'
    | '/book-launch'
    | '/coaches'
    | '/contact'
    | '/creators'
    | '/ecommerce'
    | '/faqs'
    | '/guarantee'
    | '/home-services'
    | '/hvac'
    | '/industries'
    | '/law-firms'
    | '/local-business'
    | '/med-spas'
    | '/plumbers'
    | '/privacy'
    | '/real-estate'
    | '/resources'
    | '/results'
    | '/reviews'
    | '/roofers'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/capabilities/$slug'
    | '/insights/$slug'
    | '/insights/glossary'
    | '/services/$slug'
    | '/work/$slug'
    | '/blog/'
    | '/capabilities/'
    | '/insights/'
    | '/services/'
    | '/work/'
    | '/api/admin/case-studies'
    | '/api/admin/portfolio'
    | '/api/admin/session'
    | '/api/admin/team'
    | '/api/admin/testimonials'
    | '/api/admin/upload'
    | '/api/admin/upload-url'
    | '/api/public/case-studies'
    | '/api/public/growth-audit'
    | '/api/public/inquiry'
    | '/api/public/newsletter'
    | '/api/public/portfolio'
    | '/api/public/resource-request'
    | '/api/public/team'
    | '/api/public/testimonials'
    | '/insights/answers/$slug'
    | '/insights/guides/$slug'
    | '/api/admin/case-studies/$id'
    | '/api/admin/case-studies/reorder'
    | '/api/admin/portfolio/$id'
    | '/api/admin/portfolio/reorder'
    | '/api/admin/team/$id'
    | '/api/admin/team/reorder'
    | '/api/admin/testimonials/$id'
    | '/api/admin/testimonials/reorder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AgenciesRoute: typeof AgenciesRoute
  AuthorsRoute: typeof AuthorsRoute
  BookLaunchRoute: typeof BookLaunchRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  EcommerceRoute: typeof EcommerceRoute
  FaqsRoute: typeof FaqsRoute
  GuaranteeRoute: typeof GuaranteeRoute
  HomeServicesRoute: typeof HomeServicesRoute
  HvacRoute: typeof HvacRoute
  IndustriesRoute: typeof IndustriesRoute
  LawFirmsRoute: typeof LawFirmsRoute
  LocalBusinessRoute: typeof LocalBusinessRoute
  MedSpasRoute: typeof MedSpasRoute
  PlumbersRoute: typeof PlumbersRoute
  PrivacyRoute: typeof PrivacyRoute
  RealEstateRoute: typeof RealEstateRoute
  ResourcesRoute: typeof ResourcesRoute
  ResultsRoute: typeof ResultsRoute
  ReviewsRoute: typeof ReviewsRoute
  RoofersRoute: typeof RoofersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CapabilitiesSlugRoute: typeof CapabilitiesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsGlossaryRoute: typeof InsightsGlossaryRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CapabilitiesIndexRoute: typeof CapabilitiesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
  ApiAdminCaseStudiesRoute: typeof ApiAdminCaseStudiesRouteWithChildren
  ApiAdminPortfolioRoute: typeof ApiAdminPortfolioRouteWithChildren
  ApiAdminSessionRoute: typeof ApiAdminSessionRoute
  ApiAdminTeamRoute: typeof ApiAdminTeamRouteWithChildren
  ApiAdminTestimonialsRoute: typeof ApiAdminTestimonialsRouteWithChildren
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAdminUploadUrlRoute: typeof ApiAdminUploadUrlRoute
  ApiPublicCaseStudiesRoute: typeof ApiPublicCaseStudiesRoute
  ApiPublicGrowthAuditRoute: typeof ApiPublicGrowthAuditRoute
  ApiPublicInquiryRoute: typeof ApiPublicInquiryRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
  ApiPublicPortfolioRoute: typeof ApiPublicPortfolioRoute
  ApiPublicResourceRequestRoute: typeof ApiPublicResourceRequestRoute
  ApiPublicTeamRoute: typeof ApiPublicTeamRoute
  ApiPublicTestimonialsRoute: typeof ApiPublicTestimonialsRoute
  InsightsAnswersSlugRoute: typeof InsightsAnswersSlugRoute
  InsightsGuidesSlugRoute: typeof InsightsGuidesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-launch': {
      id: '/book-launch'
      path: '/book-launch'
      fullPath: '/book-launch'
      preLoaderRoute: typeof BookLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantee': {
      id: '/guarantee'
      path: '/guarantee'
      fullPath: '/guarantee'
      preLoaderRoute: typeof GuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-services': {
      id: '/home-services'
      path: '/home-services'
      fullPath: '/home-services'
      preLoaderRoute: typeof HomeServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hvac': {
      id: '/hvac'
      path: '/hvac'
      fullPath: '/hvac'
      preLoaderRoute: typeof HvacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/law-firms': {
      id: '/law-firms'
      path: '/law-firms'
      fullPath: '/law-firms'
      preLoaderRoute: typeof LawFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-business': {
      id: '/local-business'
      path: '/local-business'
      fullPath: '/local-business'
      preLoaderRoute: typeof LocalBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/med-spas': {
      id: '/med-spas'
      path: '/med-spas'
      fullPath: '/med-spas'
      preLoaderRoute: typeof MedSpasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plumbers': {
      id: '/plumbers'
      path: '/plumbers'
      fullPath: '/plumbers'
      preLoaderRoute: typeof PlumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roofers': {
      id: '/roofers'
      path: '/roofers'
      fullPath: '/roofers'
      preLoaderRoute: typeof RoofersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/': {
      id: '/capabilities/'
      path: '/capabilities'
      fullPath: '/capabilities/'
      preLoaderRoute: typeof CapabilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities/$slug': {
      id: '/capabilities/$slug'
      path: '/capabilities/$slug'
      fullPath: '/capabilities/$slug'
      preLoaderRoute: typeof CapabilitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/glossary': {
      id: '/insights/glossary'
      path: '/insights/glossary'
      fullPath: '/insights/glossary'
      preLoaderRoute: typeof InsightsGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/case-studies': {
      id: '/api/admin/case-studies'
      path: '/api/admin/case-studies'
      fullPath: '/api/admin/case-studies'
      preLoaderRoute: typeof ApiAdminCaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/portfolio': {
      id: '/api/admin/portfolio'
      path: '/api/admin/portfolio'
      fullPath: '/api/admin/portfolio'
      preLoaderRoute: typeof ApiAdminPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/session': {
      id: '/api/admin/session'
      path: '/api/admin/session'
      fullPath: '/api/admin/session'
      preLoaderRoute: typeof ApiAdminSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/team': {
      id: '/api/admin/team'
      path: '/api/admin/team'
      fullPath: '/api/admin/team'
      preLoaderRoute: typeof ApiAdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/testimonials': {
      id: '/api/admin/testimonials'
      path: '/api/admin/testimonials'
      fullPath: '/api/admin/testimonials'
      preLoaderRoute: typeof ApiAdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-url': {
      id: '/api/admin/upload-url'
      path: '/api/admin/upload-url'
      fullPath: '/api/admin/upload-url'
      preLoaderRoute: typeof ApiAdminUploadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/case-studies': {
      id: '/api/public/case-studies'
      path: '/api/public/case-studies'
      fullPath: '/api/public/case-studies'
      preLoaderRoute: typeof ApiPublicCaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth-audit': {
      id: '/api/public/growth-audit'
      path: '/api/public/growth-audit'
      fullPath: '/api/public/growth-audit'
      preLoaderRoute: typeof ApiPublicGrowthAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inquiry': {
      id: '/api/public/inquiry'
      path: '/api/public/inquiry'
      fullPath: '/api/public/inquiry'
      preLoaderRoute: typeof ApiPublicInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portfolio': {
      id: '/api/public/portfolio'
      path: '/api/public/portfolio'
      fullPath: '/api/public/portfolio'
      preLoaderRoute: typeof ApiPublicPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resource-request': {
      id: '/api/public/resource-request'
      path: '/api/public/resource-request'
      fullPath: '/api/public/resource-request'
      preLoaderRoute: typeof ApiPublicResourceRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/team': {
      id: '/api/public/team'
      path: '/api/public/team'
      fullPath: '/api/public/team'
      preLoaderRoute: typeof ApiPublicTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/testimonials': {
      id: '/api/public/testimonials'
      path: '/api/public/testimonials'
      fullPath: '/api/public/testimonials'
      preLoaderRoute: typeof ApiPublicTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/answers/$slug': {
      id: '/insights/answers/$slug'
      path: '/insights/answers/$slug'
      fullPath: '/insights/answers/$slug'
      preLoaderRoute: typeof InsightsAnswersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/guides/$slug': {
      id: '/insights/guides/$slug'
      path: '/insights/guides/$slug'
      fullPath: '/insights/guides/$slug'
      preLoaderRoute: typeof InsightsGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/case-studies/$id': {
      id: '/api/admin/case-studies/$id'
      path: '/$id'
      fullPath: '/api/admin/case-studies/$id'
      preLoaderRoute: typeof ApiAdminCaseStudiesIdRouteImport
      parentRoute: typeof ApiAdminCaseStudiesRoute
    }
    '/api/admin/case-studies/reorder': {
      id: '/api/admin/case-studies/reorder'
      path: '/reorder'
      fullPath: '/api/admin/case-studies/reorder'
      preLoaderRoute: typeof ApiAdminCaseStudiesReorderRouteImport
      parentRoute: typeof ApiAdminCaseStudiesRoute
    }
    '/api/admin/portfolio/$id': {
      id: '/api/admin/portfolio/$id'
      path: '/$id'
      fullPath: '/api/admin/portfolio/$id'
      preLoaderRoute: typeof ApiAdminPortfolioIdRouteImport
      parentRoute: typeof ApiAdminPortfolioRoute
    }
    '/api/admin/portfolio/reorder': {
      id: '/api/admin/portfolio/reorder'
      path: '/reorder'
      fullPath: '/api/admin/portfolio/reorder'
      preLoaderRoute: typeof ApiAdminPortfolioReorderRouteImport
      parentRoute: typeof ApiAdminPortfolioRoute
    }
    '/api/admin/team/$id': {
      id: '/api/admin/team/$id'
      path: '/$id'
      fullPath: '/api/admin/team/$id'
      preLoaderRoute: typeof ApiAdminTeamIdRouteImport
      parentRoute: typeof ApiAdminTeamRoute
    }
    '/api/admin/team/reorder': {
      id: '/api/admin/team/reorder'
      path: '/reorder'
      fullPath: '/api/admin/team/reorder'
      preLoaderRoute: typeof ApiAdminTeamReorderRouteImport
      parentRoute: typeof ApiAdminTeamRoute
    }
    '/api/admin/testimonials/$id': {
      id: '/api/admin/testimonials/$id'
      path: '/$id'
      fullPath: '/api/admin/testimonials/$id'
      preLoaderRoute: typeof ApiAdminTestimonialsIdRouteImport
      parentRoute: typeof ApiAdminTestimonialsRoute
    }
    '/api/admin/testimonials/reorder': {
      id: '/api/admin/testimonials/reorder'
      path: '/reorder'
      fullPath: '/api/admin/testimonials/reorder'
      preLoaderRoute: typeof ApiAdminTestimonialsReorderRouteImport
      parentRoute: typeof ApiAdminTestimonialsRoute
    }
  }
}

interface ApiAdminCaseStudiesRouteChildren {
  ApiAdminCaseStudiesIdRoute: typeof ApiAdminCaseStudiesIdRoute
  ApiAdminCaseStudiesReorderRoute: typeof ApiAdminCaseStudiesReorderRoute
}

const ApiAdminCaseStudiesRouteChildren: ApiAdminCaseStudiesRouteChildren = {
  ApiAdminCaseStudiesIdRoute: ApiAdminCaseStudiesIdRoute,
  ApiAdminCaseStudiesReorderRoute: ApiAdminCaseStudiesReorderRoute,
}

const ApiAdminCaseStudiesRouteWithChildren =
  ApiAdminCaseStudiesRoute._addFileChildren(ApiAdminCaseStudiesRouteChildren)

interface ApiAdminPortfolioRouteChildren {
  ApiAdminPortfolioIdRoute: typeof ApiAdminPortfolioIdRoute
  ApiAdminPortfolioReorderRoute: typeof ApiAdminPortfolioReorderRoute
}

const ApiAdminPortfolioRouteChildren: ApiAdminPortfolioRouteChildren = {
  ApiAdminPortfolioIdRoute: ApiAdminPortfolioIdRoute,
  ApiAdminPortfolioReorderRoute: ApiAdminPortfolioReorderRoute,
}

const ApiAdminPortfolioRouteWithChildren =
  ApiAdminPortfolioRoute._addFileChildren(ApiAdminPortfolioRouteChildren)

interface ApiAdminTeamRouteChildren {
  ApiAdminTeamIdRoute: typeof ApiAdminTeamIdRoute
  ApiAdminTeamReorderRoute: typeof ApiAdminTeamReorderRoute
}

const ApiAdminTeamRouteChildren: ApiAdminTeamRouteChildren = {
  ApiAdminTeamIdRoute: ApiAdminTeamIdRoute,
  ApiAdminTeamReorderRoute: ApiAdminTeamReorderRoute,
}

const ApiAdminTeamRouteWithChildren = ApiAdminTeamRoute._addFileChildren(
  ApiAdminTeamRouteChildren,
)

interface ApiAdminTestimonialsRouteChildren {
  ApiAdminTestimonialsIdRoute: typeof ApiAdminTestimonialsIdRoute
  ApiAdminTestimonialsReorderRoute: typeof ApiAdminTestimonialsReorderRoute
}

const ApiAdminTestimonialsRouteChildren: ApiAdminTestimonialsRouteChildren = {
  ApiAdminTestimonialsIdRoute: ApiAdminTestimonialsIdRoute,
  ApiAdminTestimonialsReorderRoute: ApiAdminTestimonialsReorderRoute,
}

const ApiAdminTestimonialsRouteWithChildren =
  ApiAdminTestimonialsRoute._addFileChildren(ApiAdminTestimonialsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AgenciesRoute: AgenciesRoute,
  AuthorsRoute: AuthorsRoute,
  BookLaunchRoute: BookLaunchRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  EcommerceRoute: EcommerceRoute,
  FaqsRoute: FaqsRoute,
  GuaranteeRoute: GuaranteeRoute,
  HomeServicesRoute: HomeServicesRoute,
  HvacRoute: HvacRoute,
  IndustriesRoute: IndustriesRoute,
  LawFirmsRoute: LawFirmsRoute,
  LocalBusinessRoute: LocalBusinessRoute,
  MedSpasRoute: MedSpasRoute,
  PlumbersRoute: PlumbersRoute,
  PrivacyRoute: PrivacyRoute,
  RealEstateRoute: RealEstateRoute,
  ResourcesRoute: ResourcesRoute,
  ResultsRoute: ResultsRoute,
  ReviewsRoute: ReviewsRoute,
  RoofersRoute: RoofersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CapabilitiesSlugRoute: CapabilitiesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsGlossaryRoute: InsightsGlossaryRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CapabilitiesIndexRoute: CapabilitiesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
  ApiAdminCaseStudiesRoute: ApiAdminCaseStudiesRouteWithChildren,
  ApiAdminPortfolioRoute: ApiAdminPortfolioRouteWithChildren,
  ApiAdminSessionRoute: ApiAdminSessionRoute,
  ApiAdminTeamRoute: ApiAdminTeamRouteWithChildren,
  ApiAdminTestimonialsRoute: ApiAdminTestimonialsRouteWithChildren,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAdminUploadUrlRoute: ApiAdminUploadUrlRoute,
  ApiPublicCaseStudiesRoute: ApiPublicCaseStudiesRoute,
  ApiPublicGrowthAuditRoute: ApiPublicGrowthAuditRoute,
  ApiPublicInquiryRoute: ApiPublicInquiryRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
  ApiPublicPortfolioRoute: ApiPublicPortfolioRoute,
  ApiPublicResourceRequestRoute: ApiPublicResourceRequestRoute,
  ApiPublicTeamRoute: ApiPublicTeamRoute,
  ApiPublicTestimonialsRoute: ApiPublicTestimonialsRoute,
  InsightsAnswersSlugRoute: InsightsAnswersSlugRoute,
  InsightsGuidesSlugRoute: InsightsGuidesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
