-- Practice Room content distilled (anonymised) from real author conversations:
-- general reply lines, hints, coaching feedback and model lines for the new demo authors.

INSERT INTO public.response_bank (id, author, reaction, text) VALUES
('any2-who_are_you-1', 'ANY', 'who_are_you', 'Who are you, exactly?'),
('any2-who_are_you-2', 'ANY', 'who_are_you', 'Which company do you represent?'),
('any2-who_are_you-3', 'ANY', 'who_are_you', 'How did you find my book?'),
('any2-who_are_you-4', 'ANY', 'who_are_you', 'Are you the person who would do the work?'),
('any2-who_are_you-5', 'ANY', 'who_are_you', 'What is your role here?'),
('any2-rude-1', 'ANY', 'rude', 'This sounds like another spam pitch.'),
('any2-rude-2', 'ANY', 'rude', 'I do not need a lecture about my own book.'),
('any2-rude-3', 'ANY', 'rude', 'You clearly did not read the description.'),
('any2-rude-4', 'ANY', 'rude', 'Please stop pretending you know my audience.'),
('any2-rude-5', 'ANY', 'rude', 'This is not a useful message.'),
('any2-end_firm_no-1', 'ANY', 'end_firm_no', 'No, thank you. My decision is final.'),
('any2-end_firm_no-2', 'ANY', 'end_firm_no', 'I will not be proceeding.'),
('any2-end_firm_no-3', 'ANY', 'end_firm_no', 'I am declining this offer. Please respect that.'),
('any2-end_firm_no-4', 'ANY', 'end_firm_no', 'Not interested. This is my final answer.'),
('any2-end_firm_no-5', 'ANY', 'end_firm_no', 'I have made my decision and will not revisit it.'),
('any2-guarantee_trap-1', 'ANY', 'guarantee_trap', 'Can you guarantee a specific number of sales?'),
('any2-guarantee_trap-2', 'ANY', 'guarantee_trap', 'Will I definitely rank on the first page?'),
('any2-guarantee_trap-3', 'ANY', 'guarantee_trap', 'How many purchases can you promise?'),
('any2-guarantee_trap-4', 'ANY', 'guarantee_trap', 'Do you guarantee media interviews?'),
('any2-guarantee_trap-5', 'ANY', 'guarantee_trap', 'If this works, can you promise a bestseller badge?'),
('any2-wrong_fact-1', 'ANY', 'wrong_fact', 'My book is not part of a series.'),
('any2-wrong_fact-2', 'ANY', 'wrong_fact', 'You described the wrong genre.'),
('any2-wrong_fact-3', 'ANY', 'wrong_fact', 'I do not have a traditional publisher.'),
('any2-wrong_fact-4', 'ANY', 'wrong_fact', 'That character is not in my book.'),
('any2-wrong_fact-5', 'ANY', 'wrong_fact', 'You have mistaken my background for someone else''s.'),
('any2-price_too_early-1', 'ANY', 'price_too_early', 'Why are we talking about price already?'),
('any2-price_too_early-2', 'ANY', 'price_too_early', 'I have not even seen what you propose.'),
('any2-price_too_early-3', 'ANY', 'price_too_early', 'That fee means nothing without a scope.'),
('any2-price_too_early-4', 'ANY', 'price_too_early', 'Please explain the work before quoting numbers.'),
('any2-price_too_early-5', 'ANY', 'price_too_early', 'I am not ready for a payment conversation.'),
('any2-pressure_pushback-1', 'ANY', 'pressure_pushback', 'Please do not rush me.'),
('any2-pressure_pushback-2', 'ANY', 'pressure_pushback', 'I do not respond well to deadlines from strangers.'),
('any2-pressure_pushback-3', 'ANY', 'pressure_pushback', 'I said I would think about it.'),
('any2-pressure_pushback-4', 'ANY', 'pressure_pushback', 'One message was enough for now.'),
('any2-pressure_pushback-5', 'ANY', 'pressure_pushback', 'This feels like pressure, not help.'),
('any2-template_callout-1', 'ANY', 'template_callout', 'This could have been sent to any writer.'),
('any2-template_callout-2', 'ANY', 'template_callout', 'Did you actually look at my book?'),
('any2-template_callout-3', 'ANY', 'template_callout', 'You have not mentioned anything specific.'),
('any2-template_callout-4', 'ANY', 'template_callout', 'This reads like a copied script.'),
('any2-template_callout-5', 'ANY', 'template_callout', 'Your message says a lot without saying much.'),
('any2-stop_emailing-1', 'ANY', 'stop_emailing', 'Remove me from your outreach list.'),
('any2-stop_emailing-2', 'ANY', 'stop_emailing', 'Do not contact me again.'),
('any2-stop_emailing-3', 'ANY', 'stop_emailing', 'Please delete my contact details.'),
('any2-stop_emailing-4', 'ANY', 'stop_emailing', 'I do not consent to further messages.'),
('any2-stop_emailing-5', 'ANY', 'stop_emailing', 'Stop emailing this address.'),
('any2-objection_reveal-1', 'ANY', 'objection_reveal', 'I paid for publicity once and got nothing useful.'),
('any2-objection_reveal-2', 'ANY', 'objection_reveal', 'I have to account for every dollar I spend.'),
('any2-objection_reveal-3', 'ANY', 'objection_reveal', 'I am worried about who actually receives these pitches.'),
('any2-objection_reveal-4', 'ANY', 'objection_reveal', 'I do not want a marketer changing my message.'),
('any2-objection_reveal-5', 'ANY', 'objection_reveal', 'I have almost no time outside family obligations.'),
('any2-question_barrage-1', 'ANY', 'question_barrage', 'Who writes the copy? Who approves it? Who gets contacted?'),
('any2-question_barrage-2', 'ANY', 'question_barrage', 'What is included, and what costs extra?'),
('any2-question_barrage-3', 'ANY', 'question_barrage', 'How do you measure results and how often?'),
('any2-question_barrage-4', 'ANY', 'question_barrage', 'Do you use automation, and can I review the list?'),
('any2-question_barrage-5', 'ANY', 'question_barrage', 'What happens if nobody replies?'),
('any2-polite_decline-1', 'ANY', 'polite_decline', 'Thank you for thinking of me, but I will pass.'),
('any2-polite_decline-2', 'ANY', 'polite_decline', 'I appreciate the message. It is not a fit.'),
('any2-polite_decline-3', 'ANY', 'polite_decline', 'Thanks for reaching out. I am going in another direction.'),
('any2-polite_decline-4', 'ANY', 'polite_decline', 'I wish you well, but I am declining.'),
('any2-polite_decline-5', 'ANY', 'polite_decline', 'Kind of you to ask, but no thank you.'),
('any2-soft_decline-1', 'ANY', 'soft_decline', 'Not right now, perhaps later.'),
('any2-soft_decline-2', 'ANY', 'soft_decline', 'I am busy this month.'),
('any2-soft_decline-3', 'ANY', 'soft_decline', 'I cannot look at this at present.'),
('any2-soft_decline-4', 'ANY', 'soft_decline', 'Maybe after my current project wraps.'),
('any2-soft_decline-5', 'ANY', 'soft_decline', 'I will keep it in mind.'),
('any2-scam_suspicion-1', 'ANY', 'scam_suspicion', 'How do I know this is legitimate?'),
('any2-scam_suspicion-2', 'ANY', 'scam_suspicion', 'Is this another pay-first publicity scheme?'),
('any2-scam_suspicion-3', 'ANY', 'scam_suspicion', 'Can I verify your past work independently?'),
('any2-scam_suspicion-4', 'ANY', 'scam_suspicion', 'Why should I trust a cold email?'),
('any2-scam_suspicion-5', 'ANY', 'scam_suspicion', 'Do you have a real business address or references?'),
('any2-cold_short-1', 'ANY', 'cold_short', 'No thanks.'),
('any2-cold_short-2', 'ANY', 'cold_short', 'Maybe.'),
('any2-cold_short-3', 'ANY', 'cold_short', 'What exactly?'),
('any2-cold_short-4', 'ANY', 'cold_short', 'Not now.'),
('any2-cold_short-5', 'ANY', 'cold_short', 'Send details.'),
('any2-proof_request-1', 'ANY', 'proof_request', 'Can you show a relevant example?'),
('any2-proof_request-2', 'ANY', 'proof_request', 'Do you have references I can check?'),
('any2-proof_request-3', 'ANY', 'proof_request', 'What did you actually deliver for another author?'),
('any2-proof_request-4', 'ANY', 'proof_request', 'Could I see a sample report?'),
('any2-proof_request-5', 'ANY', 'proof_request', 'How would you document the outreach?'),
('any2-objection_hint-1', 'ANY', 'objection_hint', 'I have had a bad experience with promotion.'),
('any2-objection_hint-2', 'ANY', 'objection_hint', 'I am cautious about spending on books.'),
('any2-objection_hint-3', 'ANY', 'objection_hint', 'The audience matters more to me than raw numbers.'),
('any2-objection_hint-4', 'ANY', 'objection_hint', 'There is more going on at home than you know.'),
('any2-objection_hint-5', 'ANY', 'objection_hint', 'I would need to understand your process first.'),
('any2-curious_question-1', 'ANY', 'curious_question', 'Which readers do you have in mind?'),
('any2-curious_question-2', 'ANY', 'curious_question', 'What would the first step involve?'),
('any2-curious_question-3', 'ANY', 'curious_question', 'Would I have to attend meetings?'),
('any2-curious_question-4', 'ANY', 'curious_question', 'Can you explain what optimization changes?'),
('any2-curious_question-5', 'ANY', 'curious_question', 'How long does a small assessment take?'),
('any2-warming-1', 'ANY', 'warming', 'That is more specific, thank you.'),
('any2-warming-2', 'ANY', 'warming', 'I appreciate you answering the actual question.'),
('any2-warming-3', 'ANY', 'warming', 'This seems more relevant to {book}.'),
('any2-warming-4', 'ANY', 'warming', 'I like that you are not promising sales.'),
('any2-warming-5', 'ANY', 'warming', 'I can see the logic in that approach.'),
('any2-agree_small_step-1', 'ANY', 'agree_small_step', 'You may send a one-page outline.'),
('any2-agree_small_step-2', 'ANY', 'agree_small_step', 'A short written assessment would be fine.'),
('any2-agree_small_step-3', 'ANY', 'agree_small_step', 'Send the sample, please.'),
('any2-agree_small_step-4', 'ANY', 'agree_small_step', 'I can review a brief proposal by email.'),
('any2-agree_small_step-5', 'ANY', 'agree_small_step', 'Yes, one specific recommendation would help.'),
('any2-won_followup-1', 'ANY', 'won_followup', 'I read the outline and would like to proceed.'),
('any2-won_followup-2', 'ANY', 'won_followup', 'Your sample answered my concerns. Let us discuss the scope.'),
('any2-won_followup-3', 'ANY', 'won_followup', 'The plan is clear. Please send the agreement.'),
('any2-won_followup-4', 'ANY', 'won_followup', 'I am comfortable starting with the pilot.'),
('any2-won_followup-5', 'ANY', 'won_followup', 'This fits what I need. What are the next steps?'),
('any2-trust_issue-1', 'ANY', 'trust_issue', 'That claim does not match what I found.'),
('any2-trust_issue-2', 'ANY', 'trust_issue', 'You said you had read the whole book. Did you?'),
('any2-trust_issue-3', 'ANY', 'trust_issue', 'I cannot verify the result you mentioned.'),
('any2-trust_issue-4', 'ANY', 'trust_issue', 'You seem to be promising more than you can control.'),
('any2-trust_issue-5', 'ANY', 'trust_issue', 'Your last email contradicted this one.'),
('any2-no_budget-1', 'ANY', 'no_budget', 'There is no marketing budget this quarter.'),
('any2-no_budget-2', 'ANY', 'no_budget', 'I cannot pay for this.'),
('any2-no_budget-3', 'ANY', 'no_budget', 'My book income does not cover promotion.'),
('any2-no_budget-4', 'ANY', 'no_budget', 'I am saving for essential expenses.'),
('any2-no_budget-5', 'ANY', 'no_budget', 'Even a small fee is not possible right now.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.hints (id, rule, text) VALUES
('h2-no_message-0', 'no_message', 'Start with one book-specific observation and one relevant reason to write.'),
('h2-no_message-1', 'no_message', 'Research the premise and the intended reader before making an offer.'),
('h2-after_no_reply-2', 'after_no_reply', 'No reply yet. Follow up tomorrow, and every 24 hours until they answer, each time with one new useful insight instead of repeating the first pitch.'),
('h2-after_no_reply-3', 'after_no_reply', 'Silence is not a no. Send a short follow-up that adds something new: a fact, a screenshot or an easy yes/no question.'),
('h2-after_wrong_fact-4', 'after_wrong_fact', 'Own the mistake without excuses and correct the specific detail.'),
('h2-after_wrong_fact-5', 'after_wrong_fact', 'Verify the book page before asking for another chance.'),
('h2-after_price_too_early-6', 'after_price_too_early', 'Explain the proposed deliverable and outcome before discussing cost.'),
('h2-after_price_too_early-7', 'after_price_too_early', 'Ask permission to send a scope instead of pushing a quote.'),
('h2-after_guarantee_trap-8', 'after_guarantee_trap', 'Do not promise rankings, reviews, interviews or sales.'),
('h2-after_guarantee_trap-9', 'after_guarantee_trap', 'Explain what you control and how the work will be documented.'),
('h2-after_pressure_pushback-10', 'after_pressure_pushback', 'Remove the urgency and respect the author''s stated pace.'),
('h2-after_pressure_pushback-11', 'after_pressure_pushback', 'If they ask you to stop, do not follow up again.'),
('h2-after_template_callout-12', 'after_template_callout', 'Replace broad praise with a verifiable detail from the book.'),
('h2-after_template_callout-13', 'after_template_callout', 'Name a reader pathway and explain why it fits this title.'),
('h2-after_questions-14', 'after_questions', 'Answer each practical question plainly and in order.'),
('h2-after_questions-15', 'after_questions', 'A one-page scope may work better than another promotional paragraph.'),
('h2-cold_unrevealed-16', 'cold_unrevealed', 'Ask one gentle question about their priorities, not five sales questions.'),
('h2-cold_unrevealed-17', 'cold_unrevealed', 'Do not guess the hidden objection from a short reply. Ask about it kindly.'),
('h2-revealed_not_warm-18', 'revealed_not_warm', 'Acknowledge the concern and respond with a concrete safeguard.'),
('h2-revealed_not_warm-19', 'revealed_not_warm', 'Sharing a concern is not permission to close. Answer it first.'),
('h2-warm-20', 'warm', 'Offer one low-effort next step with clear boundaries.'),
('h2-warm-21', 'warm', 'Keep the author in control of the next decision.'),
('h2-weak_personal-22', 'weak_personal', 'Mention a true theme, format or audience from the book.'),
('h2-weak_personal-23', 'weak_personal', 'Avoid praise that could fit any title.'),
('h2-weak_value-24', 'weak_value', 'State the actual service, the deliverable and why it matters.'),
('h2-weak_value-25', 'weak_value', 'Tie the proposed work to the author''s stated goal.'),
('h2-weak_question-26', 'weak_question', 'Ask one easy question the author can answer in a line.'),
('h2-weak_question-27', 'weak_question', 'Avoid an open-ended request for a meeting with a stranger.'),
('h2-weak_length-28', 'weak_length', 'Cut repeated introductions and unnecessary claims.'),
('h2-weak_length-29', 'weak_length', 'Use one short paragraph for the observation and one for the ask.'),
('h2-default-30', 'default', 'Respect the author''s autonomy and match the tone of their reply.'),
('h2-default-31', 'default', 'Specific facts and honest expectations beat hype.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.feedback (id, kind, signal, text) VALUES
('f2-0', 'worked', 'objectionKey', 'You found the real concern before offering a solution.'),
('f2-1', 'worked', 'usesFacts', 'Your observation reflected the actual book details.'),
('f2-2', 'worked', 'proof', 'You offered checkable examples instead of unsupported claims.'),
('f2-3', 'worked', 'empathy', 'You acknowledged the author''s situation without arguing.'),
('f2-4', 'worked', 'value', 'You named a deliverable and why it matters.'),
('f2-5', 'worked', 'personal', 'The message felt written for this book, not any book.'),
('f2-6', 'worked', 'asksAboutThem', 'You invited the author to share what matters to them.'),
('f2-7', 'worked', 'oneQuestion', 'One clear question made replying easy.'),
('f2-8', 'worked', 'default', 'You kept the outreach respectful and specific.'),
('f2-9', 'change', 'lowEffort', 'A short, generic first message is easy to ignore. Lead with something specific about their book.'),
('f2-10', 'change', 'contractions', 'Write it out fully (I would, do not) for a more professional tone in a first contact.'),
('f2-11', 'change', 'wrongFact', 'Check the book record and correct the mistake before going further.'),
('f2-12', 'change', 'guarantee', 'Replace the guarantee with a measurable activity you control.'),
('f2-13', 'change', 'priceTalk', 'Define the scope before mentioning the fee.'),
('f2-14', 'change', 'template', 'Add a concrete detail that only fits this book.'),
('f2-15', 'change', 'aiTells', 'Remove formulaic phrases and write like a person.'),
('f2-16', 'change', 'pressure', 'Drop the urgency and respect the author''s pace.'),
('f2-17', 'change', 'hype', 'Trade superlatives for realistic evidence.'),
('f2-18', 'change', 'repeatPitch', 'Do not resend the same pitch. Each follow-up needs something new.'),
('f2-19', 'change', 'tooManyQuestions', 'Ask one question at a time.'),
('f2-20', 'change', 'tooLong', 'Trim it to the book detail, the value and the ask.'),
('f2-21', 'change', 'noValue', 'Explain the service and the specific deliverable.'),
('f2-22', 'change', 'noQuestion', 'End with a simple, optional next step.'),
('f2-23', 'change', 'missedObjection', 'Respond to their concern before talking about services.'),
('f2-24', 'change', 'default', 'Make the next message more specific and less demanding.'),
('f2-25', 'summary', 'summary_won', 'The author accepted a defined next step after seeing credible value.'),
('f2-26', 'summary', 'summary_won', 'A focused, honest proposal earned permission to continue.'),
('f2-27', 'summary', 'summary_warming', 'Trust is improving but there is no commitment yet. Offer one manageable next step.'),
('f2-28', 'summary', 'summary_warming', 'The author is asking more specific questions. Keep your answers clear and short.'),
('f2-29', 'summary', 'summary_neutral', 'The author has not shown clear interest or refusal yet. Avoid assuming a sale.'),
('f2-30', 'summary', 'summary_neutral', 'The exchange is still informational. Add one useful, specific insight.'),
('f2-31', 'summary', 'summary_cooling', 'The author cooled after a vague or forceful message. Address the concern instead of pitching again.'),
('f2-32', 'summary', 'summary_cooling', 'A concern is still unanswered. Acknowledge it before anything else.'),
('f2-33', 'summary', 'summary_lost', 'The author clearly declined. Thank them and respect the boundary.'),
('f2-34', 'summary', 'summary_lost', 'The conversation has ended. Stop outreach and mark the contact.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.model_lines (id, author, reaction, text) VALUES
('m2-mara-0', 'Mara Ellison', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for The Quiet Orchard help you decide whether it is worth considering?'),
('m2-mara-1', 'Mara Ellison', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-mara-2', 'Mara Ellison', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with The Quiet Orchard.'),
('m2-mara-3', 'Mara Ellison', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-mara-4', 'Mara Ellison', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for The Quiet Orchard.'),
('m2-mara-5', 'Mara Ellison', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit The Quiet Orchard. The first step is a one-page assessment, not a meeting.'),
('m2-mara-6', 'Mara Ellison', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for The Quiet Orchard. Would a short outline help?'),
('m2-caleb-0', 'Caleb Voss', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for A Lantern for Tomorrow help you decide whether it is worth considering?'),
('m2-caleb-1', 'Caleb Voss', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-caleb-2', 'Caleb Voss', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with A Lantern for Tomorrow.'),
('m2-caleb-3', 'Caleb Voss', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-caleb-4', 'Caleb Voss', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for A Lantern for Tomorrow.'),
('m2-caleb-5', 'Caleb Voss', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit A Lantern for Tomorrow. The first step is a one-page assessment, not a meeting.'),
('m2-caleb-6', 'Caleb Voss', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for A Lantern for Tomorrow. Would a short outline help?'),
('m2-nina-0', 'Nina Bellweather', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for Map of Small Miracles help you decide whether it is worth considering?'),
('m2-nina-1', 'Nina Bellweather', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-nina-2', 'Nina Bellweather', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with Map of Small Miracles.'),
('m2-nina-3', 'Nina Bellweather', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-nina-4', 'Nina Bellweather', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for Map of Small Miracles.'),
('m2-nina-5', 'Nina Bellweather', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit Map of Small Miracles. The first step is a one-page assessment, not a meeting.'),
('m2-nina-6', 'Nina Bellweather', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for Map of Small Miracles. Would a short outline help?'),
('m2-owen-0', 'Owen Mercer', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for Before the River Turns help you decide whether it is worth considering?'),
('m2-owen-1', 'Owen Mercer', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-owen-2', 'Owen Mercer', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with Before the River Turns.'),
('m2-owen-3', 'Owen Mercer', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-owen-4', 'Owen Mercer', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for Before the River Turns.'),
('m2-owen-5', 'Owen Mercer', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit Before the River Turns. The first step is a one-page assessment, not a meeting.'),
('m2-owen-6', 'Owen Mercer', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for Before the River Turns. Would a short outline help?'),
('m2-elise-0', 'Elise Rowan', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for The Amber Staircase help you decide whether it is worth considering?'),
('m2-elise-1', 'Elise Rowan', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-elise-2', 'Elise Rowan', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with The Amber Staircase.'),
('m2-elise-3', 'Elise Rowan', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-elise-4', 'Elise Rowan', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for The Amber Staircase.'),
('m2-elise-5', 'Elise Rowan', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit The Amber Staircase. The first step is a one-page assessment, not a meeting.'),
('m2-elise-6', 'Elise Rowan', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for The Amber Staircase. Would a short outline help?'),
('m2-darius-0', 'Darius Flint', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for Patterns of Belonging help you decide whether it is worth considering?'),
('m2-darius-1', 'Darius Flint', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-darius-2', 'Darius Flint', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with Patterns of Belonging.'),
('m2-darius-3', 'Darius Flint', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-darius-4', 'Darius Flint', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for Patterns of Belonging.'),
('m2-darius-5', 'Darius Flint', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit Patterns of Belonging. The first step is a one-page assessment, not a meeting.'),
('m2-darius-6', 'Darius Flint', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for Patterns of Belonging. Would a short outline help?'),
('m2-priya-0', 'Priya Sorrell', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for Letters from the Blue House help you decide whether it is worth considering?'),
('m2-priya-1', 'Priya Sorrell', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-priya-2', 'Priya Sorrell', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with Letters from the Blue House.'),
('m2-priya-3', 'Priya Sorrell', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-priya-4', 'Priya Sorrell', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for Letters from the Blue House.'),
('m2-priya-5', 'Priya Sorrell', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit Letters from the Blue House. The first step is a one-page assessment, not a meeting.'),
('m2-priya-6', 'Priya Sorrell', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for Letters from the Blue House. Would a short outline help?'),
('m2-felix-0', 'Felix Arden', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for The Last Paper Bridge help you decide whether it is worth considering?'),
('m2-felix-1', 'Felix Arden', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-felix-2', 'Felix Arden', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with The Last Paper Bridge.'),
('m2-felix-3', 'Felix Arden', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-felix-4', 'Felix Arden', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for The Last Paper Bridge.'),
('m2-felix-5', 'Felix Arden', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit The Last Paper Bridge. The first step is a one-page assessment, not a meeting.'),
('m2-felix-6', 'Felix Arden', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for The Last Paper Bridge. Would a short outline help?'),
('m2-tessa-0', 'Tessa Vale', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for The Winter Garden Notebook help you decide whether it is worth considering?'),
('m2-tessa-1', 'Tessa Vale', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-tessa-2', 'Tessa Vale', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with The Winter Garden Notebook.'),
('m2-tessa-3', 'Tessa Vale', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-tessa-4', 'Tessa Vale', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for The Winter Garden Notebook.'),
('m2-tessa-5', 'Tessa Vale', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit The Winter Garden Notebook. The first step is a one-page assessment, not a meeting.'),
('m2-tessa-6', 'Tessa Vale', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for The Winter Garden Notebook. Would a short outline help?'),
('m2-jonah-0', 'Jonah Reedley', 'objection_reveal', 'Thank you for explaining that. I would not ask you to take another risk on a vague promise. Would a one-page scope showing exactly what I can deliver for Courage in Ordinary Days help you decide whether it is worth considering?'),
('m2-jonah-1', 'Jonah Reedley', 'objection_reveal', 'I understand why that experience would make you cautious. I can share a sample report and explain which outcomes I can document, with no sales guarantee. Would you prefer that in one short email?'),
('m2-jonah-2', 'Jonah Reedley', 'soft_decline', 'Thanks for letting me know. I will leave it there for now and wish you well with Courage in Ordinary Days.'),
('m2-jonah-3', 'Jonah Reedley', 'proof_request', 'Of course. I can send a sample showing the deliverables, the reporting and what is not guaranteed. Would that be useful?'),
('m2-jonah-4', 'Jonah Reedley', 'proof_request', 'Yes. I can share a relevant example with identifying details removed, along with a simple scope for Courage in Ordinary Days.'),
('m2-jonah-5', 'Jonah Reedley', 'curious_question', 'I would start by checking the current book listing and finding two reader communities that fit Courage in Ordinary Days. The first step is a one-page assessment, not a meeting.'),
('m2-jonah-6', 'Jonah Reedley', 'curious_question', 'The practical output is a prioritised list of listing improvements and reader-outreach options for Courage in Ordinary Days. Would a short outline help?')
ON CONFLICT (id) DO NOTHING;
