// GENERATED by scripts/generate-industry-heads.ts -- do not edit by hand.
// Just the fields industry route <head>s need, so route configs (which sit in
// the shared bundle every page loads) don't pull in all industry page copy.
import type { Industry } from "./industries";

export type IndustryHead = Pick<Industry, "slug" | "path" | "name" | "shortName" | "seo" | "faqs">;

export const INDUSTRY_HEADS: Record<string, IndustryHead> = {
  authors: {
    slug: "authors",
    path: "/authors",
    name: "Authors & Publishers",
    shortName: "Authors & Publishers",
    seo: {
      title: "Author & Publisher Growth System | HQ360",
      description:
        "HQ360 connects brand, book funnels, SEO, advertising and automation into one growth system for authors and publishers, built to turn discovery into repeat sales.",
    },
    faqs: [
      {
        q: "Do you work with self-published and traditionally published authors?",
        a: "Both, plus small presses running multiple titles. The listing, review and platform work applies either way; the launch plan adapts to how much control you have over price and metadata.",
      },
      {
        q: "Can you guarantee a bestseller badge?",
        a: "No. We set a realistic target from category data, tell you what it would take, and run the campaign to it. Anyone promising a list placement is not being straight with you.",
      },
      {
        q: "Do you buy or incentivise reviews?",
        a: "Never. Reviews come from real readers who received and read the book, through compliant follow-up.",
      },
      {
        q: "What if my book is already published?",
        a: "A backlist relaunch is common. New categories, a rewritten description, a review push and a press run can bring a quiet title back.",
      },
    ],
  },
  creators: {
    slug: "creators",
    path: "/ugc-creators",
    name: "Content & UGC Creators",
    shortName: "Content Creators",
    seo: {
      title: "UGC & Content Creator Growth Services | HQ360",
      description:
        "Branding, portfolio websites, Canva portfolios, SEO, social media and client acquisition systems for UGC and professional content creators.",
    },
    faqs: [
      {
        q: "Do I need a portfolio website as a UGC creator?",
        a: "You need a credible place for a brand to evaluate your work and contact you. That can be a focused website, a professional creator site or a well-structured Canva portfolio, depending on your stage.",
      },
      {
        q: "Can HQ360 build my UGC portfolio in Canva?",
        a: "Yes. We can structure and design a mobile-friendly Canva portfolio with your positioning, work, services, proof and brand inquiry path.",
      },
      {
        q: "Do I need a large following to work with brands?",
        a: "No. UGC is often purchased for the quality, relevance and usability of the content, not the creator's audience size. A clear offer and strong portfolio make that distinction easier to understand.",
      },
      {
        q: "Can you help organize my brand outreach?",
        a: "Yes. We can help define a relevant prospecting approach, create personalized pitch frameworks and set up a pipeline so opportunities do not live only in scattered DMs and email threads.",
      },
      {
        q: "Can HQ360 set up a CRM for my collaborations?",
        a: "Yes. A creator CRM can track prospects, briefs, proposals, production, delivery, follow-up and rebooking without making your outreach robotic or spammy.",
      },
      {
        q: "Do you guarantee brand deals or search rankings?",
        a: "No. We build the positioning, discovery and acquisition systems intended to improve your ability to generate and convert opportunities. Outcomes depend on your work, market, offer and execution.",
      },
      {
        q: "Can you help turn one-off collaborations into repeat work?",
        a: "Yes. We can map feedback, testimonial, follow-up, new-idea and rebooking moments into a repeat-client or retainer workflow.",
      },
      {
        q: "Can you work with creators outside the USA?",
        a: "Yes. The system is designed for creators and brands working across markets. Location, language, platform and commercial requirements are considered during planning.",
      },
    ],
  },
  coaches: {
    slug: "coaches",
    path: "/coaches",
    name: "Coaches & Consultants",
    shortName: "Coaches & Consultants",
    seo: {
      title: "Client Acquisition Systems for Coaches & Consultants | HQ360",
      description:
        "HQ360 builds positioning, application funnels, paid traffic and nurture that fill a coach or consultant's calendar with qualified calls.",
    },
    faqs: [
      {
        q: "I sell high-ticket. Will paid ads work?",
        a: "Yes, when the funnel qualifies hard and the nurture does the selling. The goal is fewer, better calls, not cheap leads.",
      },
      {
        q: "Do you write the offer for me?",
        a: "We pressure-test and refine it with you. A weak offer is the most common reason a good funnel underperforms.",
      },
      {
        q: "How fast can this be live?",
        a: "A first version of the funnel and campaigns is usually live within three to four weeks, then optimised from real data.",
      },
    ],
  },
  "home-services": {
    slug: "home-services",
    path: "/home-services",
    name: "Home Service Businesses",
    shortName: "Home Services",
    seo: {
      title: "Lead Generation Agency for Home Service Businesses | HQ360",
      description:
        "HQ360 builds local ads, booking-focused websites, speed-to-lead texting and review systems that book more jobs for home service businesses.",
    },
    faqs: [
      {
        q: "We already buy leads from a directory. Should we stop?",
        a: "Not immediately. We build channels you own alongside it, then you can reduce the bought spend as your own pipeline stabilises.",
      },
      {
        q: "Do you handle multiple service areas or trades?",
        a: "Yes. Landing pages and campaigns are structured by service and location so reporting stays clear.",
      },
      {
        q: "Can this connect to our scheduling software?",
        a: "In most cases, yes, through direct integrations or Zapier and Make, so leads and jobs stay in sync.",
      },
    ],
  },
  plumbers: {
    slug: "plumbers",
    path: "/plumbers",
    name: "Plumbing Companies",
    shortName: "Plumbers",
    seo: {
      title: "Marketing Agency for Plumbing Companies | HQ360",
      description:
        "HQ360 builds local search, emergency-intent ads, instant lead response and review systems that fill plumbers' schedules with booked jobs.",
    },
    faqs: [
      {
        q: "Most of our work is emergencies. Does content matter?",
        a: "Less than response speed and local visibility. We prioritise the Google Business Profile, search ads and instant response first.",
      },
      {
        q: "Can you route leads to an on-call phone after hours?",
        a: "Yes. Call routing and text-back rules are set to your schedule so urgent jobs always reach someone.",
      },
      {
        q: "How quickly could we see more calls?",
        a: "Profile and ad changes can lift call volume within the first few weeks. Organic ranking takes longer and we report the leading indicators.",
      },
    ],
  },
  roofers: {
    slug: "roofers",
    path: "/roofers",
    name: "Roofing Companies",
    shortName: "Roofers",
    seo: {
      title: "Marketing Agency for Roofing Companies | HQ360",
      description:
        "HQ360 builds paid lead generation, inspection funnels, speed-to-lead response and estimate follow-up that book more roofing jobs.",
    },
    faqs: [
      {
        q: "Can you scale spend up after a storm and down afterward?",
        a: "Yes. Campaigns are built to flex with demand so you are not paying for volume you cannot service.",
      },
      {
        q: "Do you help with insurance-claim jobs?",
        a: "We build the content and follow-up that guide homeowners through the process. The claim itself stays with you and the adjuster.",
      },
      {
        q: "Is this only for retail, or commercial too?",
        a: "Both, with separate funnels and messaging. Commercial runs a longer nurture and a different proof set.",
      },
    ],
  },
  hvac: {
    slug: "hvac",
    path: "/hvac",
    name: "HVAC Companies",
    shortName: "HVAC",
    seo: {
      title: "Marketing Agency for HVAC Companies | HQ360",
      description:
        "HQ360 builds seasonal demand campaigns, maintenance-plan funnels, replacement follow-up and reactivation that keep HVAC crews booked year-round.",
    },
    faqs: [
      {
        q: "Can you import our service history for reactivation?",
        a: "Yes, in most cases, through a CRM import or an integration with your field-service software. Clean data makes reactivation the fastest win.",
      },
      {
        q: "Do you sell the maintenance plan for us?",
        a: "We build the offer, the page and the follow-up. Your team still closes, but with a system prompting every touchpoint.",
      },
      {
        q: "Is financing messaging compliant?",
        a: "We follow your financing partner's approved language and disclosures. We do not invent terms.",
      },
    ],
  },
  "med-spas": {
    slug: "med-spas",
    path: "/med-spas",
    name: "Med Spas & Beauty Businesses",
    shortName: "Med Spas & Beauty",
    seo: {
      title: "Marketing Agency for Med Spas & Beauty Businesses | HQ360",
      description:
        "HQ360 builds compliant local ads, treatment booking funnels, membership growth and rebooking automation that keep a med spa's calendar full.",
    },
    faqs: [
      {
        q: "Our ad account keeps getting flagged. Can you fix that?",
        a: "Often. Most restrictions come from claims and imagery that break platform policy. We build campaigns to the rules and keep the account healthy.",
      },
      {
        q: "Can this integrate with our booking software?",
        a: "Usually yes, so appointments, reminders and follow-up stay connected to the system your front desk uses.",
      },
      {
        q: "Do you provide the before-and-after content?",
        a: "We direct and edit what you capture in-clinic, within consent and platform requirements. We do not fabricate results imagery.",
      },
    ],
  },
  "real-estate": {
    slug: "real-estate",
    path: "/real-estate",
    name: "Real Estate Agents & Teams",
    shortName: "Real Estate",
    seo: {
      title: "Digital Growth Agency for Real Estate Agents | HQ360",
      description:
        "HQ360 builds lead generation, high-converting landing pages, GoHighLevel CRM and automated follow-up that book more appointments for real estate agents and teams.",
    },
    faqs: [
      {
        q: "We already use a CRM. Do we have to switch?",
        a: "Not necessarily. We work primarily in GoHighLevel, but we assess what you have and recommend switching only if the gains clearly justify it.",
      },
      {
        q: "Do you guarantee a number of listings or deals?",
        a: "No. We set appointment targets from your market and ad budget, report weekly, and adjust. Transaction outcomes depend on your sales process too.",
      },
      {
        q: "Can this work for a solo agent, not just a team?",
        a: "Yes. The system scales down — a solo agent benefits most from speed-to-lead and database reactivation.",
      },
      {
        q: "Who owns the ad account and CRM?",
        a: "You do. Everything is built in your accounts so it keeps running if we part ways.",
      },
    ],
  },
  "law-firms": {
    slug: "law-firms",
    path: "/law-firms",
    name: "Law Firms & Professional Services",
    shortName: "Law & Professional Services",
    seo: {
      title: "Growth Agency for Law Firms & Professional Services | HQ360",
      description:
        "HQ360 builds visibility, intake automation, nurture and reputation systems that help law firms and professional practices sign more of the right clients.",
    },
    faqs: [
      {
        q: "Is marketing automation compliant for a regulated practice?",
        a: "Handled properly, yes. We work within your jurisdiction's advertising rules and your professional body's guidance, and we keep messaging factual.",
      },
      {
        q: "We do not want more volume, we want better matters.",
        a: "That is the point of the qualification step. The system is tuned to sign the right work, not to maximise raw enquiries.",
      },
      {
        q: "Can you work across several practice areas?",
        a: "Yes. Each area gets its own pages, campaigns and intake routing so reporting and follow-up stay clear.",
      },
    ],
  },
  agencies: {
    slug: "agencies",
    path: "/agencies",
    name: "Agencies",
    shortName: "Agencies",
    seo: {
      title: "Growth & White-Label Delivery for Agencies | HQ360",
      description:
        "HQ360 builds positioning, outbound and inbound systems and white-label delivery capacity so agencies win better retainers without founder-only sales.",
    },
    faqs: [
      {
        q: "Is the white-label work truly under our brand?",
        a: "Yes. No HQ360 branding on deliverables or client-facing communication unless you want us named.",
      },
      {
        q: "Will you take our clients?",
        a: "No. White-label engagements include a non-solicitation agreement.",
      },
      {
        q: "Can you only do the growth side, not delivery?",
        a: "Yes. Positioning, outbound and inbound systems stand on their own. Delivery capacity is there if and when you need it.",
      },
    ],
  },
  "local-business": {
    slug: "local-business",
    path: "/local-businesses",
    name: "Local Businesses",
    shortName: "Local Business",
    seo: {
      title: "Local Business Marketing & Lead Generation | HQ360",
      description:
        "HQ360 builds Google Business Profile, local ads, offer funnels, review generation and reactivation that turn nearby searches into regulars.",
    },
    faqs: [
      {
        q: "We are a single location. Is this overkill?",
        a: "No. A single location benefits most from the basics done well — profile, reviews, a first-visit offer and a list.",
      },
      {
        q: "We do not collect emails. Can you still help?",
        a: "Yes. Setting up simple capture — a first-visit offer or loyalty sign-up — is usually the highest-return first step.",
      },
      {
        q: "Do you handle the ads and the creative?",
        a: "Yes, both, plus the tracking so you can see which campaigns bring people through the door.",
      },
    ],
  },
  ecommerce: {
    slug: "ecommerce",
    path: "/ecommerce",
    name: "E-commerce & DTC Brands",
    shortName: "E-commerce & DTC",
    seo: {
      title: "E-commerce & DTC Growth Services | HQ360",
      description:
        "HQ360 connects e-commerce branding, storefront design, SEO, acquisition, automation, retention and optimization into one growth system for product brands.",
    },
    faqs: [
      {
        q: "Can HQ360 redesign my existing store, or improve it without a full rebuild?",
        a: "Both. Often the highest-return work is targeted — rebuilding product and collection pages, fixing mobile checkout friction and adding recovery flows — without touching the rest of the store. The audit tells us which.",
      },
      {
        q: "Do you work with Shopify and WooCommerce?",
        a: "Yes, both. If you're on another platform, tell us what it is and we'll say honestly whether we can support it well or would recommend a migration.",
      },
      {
        q: "Can you set up abandoned-cart and email marketing for my store?",
        a: "Yes. We build browse, cart and checkout recovery plus welcome, post-purchase and win-back flows, usually in Klaviyo or Omnisend, integrated with your store.",
      },
      {
        q: "Do you provide e-commerce SEO?",
        a: "Yes — product and collection keyword research, technical SEO, product structured data, internal linking, and product-feed optimisation for Google Shopping. No guaranteed rankings; anyone promising those isn't being straight with you.",
      },
      {
        q: "Can you help with Meta or Google Ads?",
        a: "Yes, where the product category and platform policies allow. Some categories have advertising restrictions, so we check eligibility before recommending a channel or promising spend.",
      },
      {
        q: "Do you guarantee sales, ROAS or a revenue increase?",
        a: "No. We set realistic targets from your data, tell you what it would take, and report against them. Guaranteed revenue or ROAS claims in e-commerce are a red flag.",
      },
      {
        q: "Can you work with stores outside the USA?",
        a: "Yes. The team works remotely across time zones and a large share of clients are in the USA, but the work isn't US-only.",
      },
      {
        q: "Do I need every stage of the growth system?",
        a: "No. Most brands start with one or two — usually storefront CRO and cart recovery. We identify the biggest current bottleneck and begin there.",
      },
    ],
  },
};
